### ISSUE TITLE
pdf upscale not working

### ISSUE THREAD

**Issue by nvmend** [Tenpi/Waifu2x-GUI#18] opened 2024-02-19 03:14 UTC
pdf not working, after finish it result in a pdf file of 15kb and says that cant open it

**Comment by Tenpi** [comment] 2024-02-19 22:10
Does it output the pages and upscale each page?

**Comment by puff-dayo** [comment] 2024-02-20 18:40
OS: Windows 11 21H2 x64
Waifu2x-GUI Version: 0.4.7 (latest)

I used a mixed image and text layout pdf file for testing and reproduced the same problem.
Attached are the input files and all the files output by Waifu2x-GUI.
[Test PDF file and output.zip](https://github.com/Tenpi/Waifu2x-GUI/files/14349847/Test.PDF.file.and.output.zip)

Thank you for developing, and I'm happy to help with any further testing.

**Comment by Tenpi** [comment] 2024-02-23 00:56
update to 0.4.8 and tell me if that works

**Comment by puff-dayo** [comment] 2024-02-25 14:59
![Image](https://github.com/Tenpi/Waifu2x-GUI/assets/84665734/5b0d80a6-dd22-41ec-9412-2036b7884cd3)

After uninstalling & reinstalling to version 0.4.8, its GUI no longer appears and the folder it is looking for in the %Temp% directory doesn't exist

**Comment by Tenpi** [comment] 2024-02-25 23:47
Reinstall the same version 0.4.8 again

**Comment by puff-dayo** [comment] 2024-03-02 13:03
> After uninstalling & reinstalling to version 0.4.8, its GUI no longer appears and the folder it is looking for in the %Temp% directory doesn't exist

The problem seems to be that although I specified the install path to drive E, the installer writes about 1.5GB of temporary data to drive C and then cleans it. If the C drive does not have enough space for the temporary data, subsequent installations will report an error.

> update to 0.4.8 and tell me if that works

Updated to the latest version and the PDF upscale process seems to be working fine. But the problem now is that the model is reading each page of the PDF (A4 paper size) at 612x792 resolution as input, resulting in a lot of raw information being lost. Hopefully maybe if allowed to manually specify the resolution of the PDF read in would be better.

Thanks a lot. 😊

**Comment by Tenpi** [comment] 2024-03-02 19:41
Set PDF downscale to 0 to extract each page at the original resolution and turn on PNG frames to extract as a png which is a lossless format. The size in pixels will be inches * dpi, if you saved at a low dpi it will be pretty small.

**Closed** 2024-03-02 19:41 UTC
